Update check_elasticsearch

diff --git a/check_elasticsearch b/check_elasticsearch
--- a/check_elasticsearch
+++ b/check_elasticsearch
@@ -18,6 +18,7 @@ PROGNAME=`basename $0`
 VERSION="Version 0.2.0,"
 AUTHOR="Andrew Lyon, Based on Mike Adolphs (http://www.matejunkie.com/) check_nginx.sh code"
 
+
 ST_OK=0
 ST_WR=1
 ST_CR=2
@@ -28,7 +29,6 @@ port=9200
 status_page="/_cluster/health"
 output_dir=/tmp
 secure=0
-carbon_key="system.:::name:::.cluster.app.elasticsearch.cluster"
 
 print_version() {
     echo "$VERSION $AUTHOR"
@@ -38,8 +38,8 @@ print_help() {
     print_version $PROGNAME $VERSION
     echo ""
     echo "$PROGNAME is a Nagios plugin to check the cluster status of elasticsearch."
-    echo "It also parses the status page to get a few useful variables out, and return"
-    echo "them in the output."
+	echo "It also parses the status page to get a few useful variables out, and return"
+	echo "them in the output."
     echo ""
     echo "$PROGNAME -H localhost -P 9200 -o /tmp"
     echo ""
@@ -76,23 +76,19 @@ while test -n "$1"; do
             output_dir=$2
             shift
             ;;
-        --carbon-server|-c)
+	--carbon-server|-c)
             carbon_server=$2
             shift
             ;;
-        --carbon-port|-C)
+	--carbon-port|-C)
             carbon_port=$2
             shift
             ;;
-        --carbon-key|-k)
-            carbon_key=$2
-            shift
-            ;;
         *)
-        echo "Unknown argument: $1"
-        print_help
-        exit $ST_UK
-        ;;
+            echo "Unknown argument: $1"
+            print_help
+            exit $ST_UK
+            ;;
     esac
     shift
 done
@@ -101,37 +97,42 @@ get_status() {
     filename=${PROGNAME}-${hostname}-${status_page}.1
     filename=`echo $filename | tr -d '\/'`
     filename=${output_dir}/${filename}
-    wget -q -t 3 -T 3 http://${hostname}:${port}/${status_page}?pretty=true -O ${filename}
+	wget -q -t 3 -T 3 http://${hostname}:${port}${status_page}?pretty=true -O ${filename}
 }
 
 get_vals() {
-    name=$(grep '"cluster_name" :' ${filename} | awk -F '"' '{print $4}')
-    status=$(grep '"status" :' ${filename} | awk -F '"' '{print $4}')
-    timed_out=`grep timed_out ${filename} | awk '{print $3}' | sed 's|[\r",]||g'`
-    number_nodes=`grep number_of_nodes ${filename} | awk '{print $3}' | sed 's|[\r",]||g'`
-    number_data_nodes=`grep number_of_data_nodes ${filename} | awk '{print $3}' | sed 's|[\r",]||g'`
-    active_primary_shards=`grep active_primary_shards ${filename} | awk '{print $3}' | sed 's|[\r",]||g'`
-    active_shards=`grep active_shards ${filename} | awk '{print $3}' | sed 's|[\r",]||g'`
-    relocating_shards=`grep relocating_shards ${filename} | awk '{print $3}' | sed 's|[\r",]||g'`
-    initializing_shards=`grep initializing_shards ${filename} | awk '{print $3}' | sed 's|[\r",]||g'`
-    delayed_unassigned_shards=`grep delayed_unassigned_shards ${filename} | awk '{print $3}' | sed 's|[\r",]||g'`
-    unassigned_shards=`grep -w '"unassigned_shards' ${filename} | awk '{print $3}' | sed 's|[\r",]||g'`
-    rm -f ${filename}
+	#name=`grep cluster_name ${filename} | awk '{print $3}' | sed 's|[\r",]||g'`
+	name=`grep cluster_name ${filename} | awk 'BEGIN { FS = " : " } ; {print $2}' | sed 's|[\r",]||g'`
+	status=`grep status ${filename} | awk '{print $3}' | sed 's|[\r",]||g'`
+	timed_out=`grep timed_out ${filename} | awk '{print $3}' | sed 's|[\r",]||g'`
+	number_nodes=`grep number_of_nodes ${filename} | awk '{print $3}' | sed 's|[\r",]||g'`
+	number_data_nodes=`grep number_of_data_nodes ${filename} | awk '{print $3}' | sed 's|[\r",]||g'`
+	active_primary_shards=`grep active_primary_shards ${filename} | awk '{print $3}' | sed 's|[\r",]||g'`
+	active_shards=`grep active_shards ${filename} | awk '{print $3}' | sed 's|[\r",]||g'`
+	relocating_shards=`grep relocating_shards ${filename} | awk '{print $3}' | sed 's|[\r",]||g'`
+	initializing_shards=`grep initializing_shards ${filename} | awk '{print $3}' | sed 's|[\r",]||g'`
+	unassigned_shards=`grep unassigned_shards ${filename} | awk '{print $3}' | sed 's|[\r",]||g'`
+	delayed_unassigned_shards=`grep delayed_unassigned_shards ${filename} | awk '{print $3}' | sed 's|[\r",]||g'`
+	number_of_pending_tasks=`grep number_of_pending_tasks ${filename} | awk '{print $3}' | sed 's|[\r",]||g'`
+	number_of_in_flight_fetch=`grep number_of_in_flight_fetch ${filename} | awk '{print $3}' | sed 's|[\r",]||g'`
+	task_max_waiting_in_queue_millis=`grep task_max_waiting_in_queue_millis ${filename} | awk '{print $3}' | sed 's|[\r",]||g'`
+	active_shards_percent_as_number=`grep active_shards_percent_as_number ${filename} | awk '{print $3}' | sed 's|[\r",]||g'`
+	rm -f ${filename}
 
-    # Determine the Nagios Status and Exit Code
-    if [ "$status" = "red" ]; then
-        NAGSTATUS="CRITICAL"
-        EXST=$ST_CR
-    elif [ "$status" = "yellow" ]; then
-        NAGSTATUS="WARNING"
-        EXST=$ST_WR
-    elif [ "$status" = "green" ]; then
-        NAGSTATUS="OK"
-        EXST=$ST_OK
-    else
-        NAGSTATUS="UNKNOWN"
-        EXST=$ST_UK
-    fi
+	# Determine the Nagios Status and Exit Code
+	if [ "$status" = "red" ]; then
+		NAGSTATUS="CRITICAL"
+		EXST=$ST_CR
+	elif [ "$status" = "yellow" ]; then
+		NAGSTATUS="WARNING"
+		EXST=$ST_WR
+	elif [ "$status" = "green" ]; then
+		NAGSTATUS="OK"
+		EXST=$ST_OK
+	else
+		NAGSTATUS="UNKNOWN"
+		EXST=$ST_UK
+	fi
 }
 
 do_output() {
@@ -144,51 +145,52 @@ active_primary_shards: $active_primary_shards; \
 active_shards: $active_shards; \
 relocating_shards: $relocating_shards; \
 initializing_shards: $initializing_shards; \
+unassigned_shards: $unassigned_shards; \
 delayed_unassigned_shards: $delayed_unassigned_shards; \
-unassigned_shards: $unassigned_shards "
+number_of_pending_tasks: $number_of_pending_tasks; \
+number_of_in_flight_fetch: $number_of_in_flight_fetch; \
+task_max_waiting_in_queue_millis: $task_max_waiting_in_queue_millis; \
+active_shards_percent_as_number: $active_shards_percent_as_number "
 }
 
 do_perfdata() {
     #perfdata="'idle'=$iproc 'active'=$aproc 'total'=$tproc"
-    perfdata="'active_primary'=$active_primary_shards 'active'=$active_shards 'relocating'=$relocating_shards 'init'=$initializing_shards 'delay_unass'=$delayed_unassigned_shards 'unass'=$unassigned_shards"
+    perfdata="'active_primary'=$active_primary_shards 'active'=$active_shards 'relocating'=$relocating_shards 'init'=$initializing_shards 'unass'=$unassigned_shards"
 }
 
 do_graphite() {
-    if [ "$carbon_server" != "" -a "$carbon_port" != "" ]; then
-        key=$(echo $carbon_key | sed "s/:::name:::/$name/")
-        echo "$key.cluster.status                $EXST                  $epoch" | nc -w 2 $carbon_server $carbon_port
-        echo "$key.cluster.nodes.ttl             $number_nodes          $epoch" | nc -w 2 $carbon_server $carbon_port
-        echo "$key.cluster.nodes.data            $number_data_nodes     $epoch" | nc -w 2 $carbon_server $carbon_port
-        echo "$key.cluster.shards.active         $active_shards         $epoch" | nc -w 2 $carbon_server $carbon_port
-        echo "$key.cluster.shards.active_primary $active_primary_shards $epoch" | nc -w 2 $carbon_server $carbon_port
-        echo "$key.cluster.shards.initializing   $initializing_shards   $epoch" | nc -w 2 $carbon_server $carbon_port
-        echo "$key.cluster.shards.relocating     $relocating_shards     $epoch" | nc -w 2 $carbon_server $carbon_port
-        echo "$key.cluster.shards.delayed_unassigned     $delayed_unassigned_shards     $epoch" | nc -w 2 $carbon_server $carbon_port
-        echo "$key.cluster.shards.unassigned     $unassigned_shards     $epoch" | nc -w 2 $carbon_server $carbon_port
-        unset key
-    fi
+	if [ "$carbon_server" != "" -a "$carbon_port" != "" ]; then
+		echo "system.$name.cluster.app.elasticsearch.cluster.status                $EXST                  $epoch" | nc -w 2 $carbon_server $carbon_port
+		echo "system.$name.cluster.app.elasticsearch.cluster.nodes.ttl             $number_nodes          $epoch" | nc -w 2 $carbon_server $carbon_port
+		echo "system.$name.cluster.app.elasticsearch.cluster.nodes.data            $number_data_nodes     $epoch" | nc -w 2 $carbon_server $carbon_port
+		echo "system.$name.cluster.app.elasticsearch.cluster.shards.active         $active_shards         $epoch" | nc -w 2 $carbon_server $carbon_port
+		echo "system.$name.cluster.app.elasticsearch.cluster.shards.active_primary $active_primary_shards $epoch" | nc -w 2 $carbon_server $carbon_port
+		echo "system.$name.cluster.app.elasticsearch.cluster.shards.initializing   $initializing_shards   $epoch" | nc -w 2 $carbon_server $carbon_port
+		echo "system.$name.cluster.app.elasticsearch.cluster.shards.relocating     $relocating_shards     $epoch" | nc -w 2 $carbon_server $carbon_port
+		echo "system.$name.cluster.app.elasticsearch.cluster.shards.unassigned     $unassigned_shards     $epoch" | nc -w 2 $carbon_server $carbon_port
+	fi
 }
 
 # Here we go!
 which wget >/dev/null 2>&1
 if [ "$?" != "0" ]; then
-    echo "CRITICAL - wget is not installed"
-    exit $ST_CR
+        echo "CRITICAL - wget is not installed"
+        exit $ST_CR
 fi
 get_status
 if [ ! -s "$filename" ]; then
-    echo "CRITICAL - Could not connect to server $hostname"
-    exit $ST_CR
-else
-    get_vals
-    if [ -z "$name" ]; then
-        echo "CRITICAL - Error parsing server output"
+        echo "CRITICAL - Could not connect to server $hostname"
         exit $ST_CR
-    else
-        do_output
-        do_perfdata
-    do_graphite
-    fi
+else
+        get_vals
+        if [ -z "$name" ]; then
+                echo "CRITICAL - Error parsing server output"
+                exit $ST_CR
+        else
+                do_output
+                do_perfdata
+		do_graphite
+        fi
 fi
 
 COMPARE=$listql
